language: node_js

node_js:
  - lts/*

cache: npm

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: lts/*
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
