language: node_js

node_js:
  - lts/*

cache: npm

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      if: (branch = release) AND (type = push)
      node_js: lts/*
      script: npm run release:semantic

notifications:
  slack: envisage-as:m8dioePQhKyI7s0dJEQcKTI7
  on_success: always
